### ISSUE TITLE
Readability on mobile

### ISSUE THREAD

**Issue by otech-nl** [ag91/ag91.github.io#1]
Hello Andrea,

Thank you for sharing your thoughts through this blog. I would like to follow along, but unfortunately, the CSS/styling makes it very hard to read for me on mobile, because the font is very big (see attached tablet screenshot).

What would help:
- (my preference) full text in RSS, instead of just a teaser, so I can read in my feed reader
- scaling fonts (it seems font-size is fixed and not relative to screen size)

Regards
![Screenshot_2021-06-24-06-49-15-045](https://user-images.githubusercontent.com/13872082/123204982-6268b680-d4b9-11eb-9905-46d17b742f43.png)

**Comment by ag91** [comment]
hi @otech-nl , sorry for the late reply. I am looking into this: I should save the day by fixing the css used. I will update here if I manage

**Comment by ag91** [comment]
@otech-nl please let me know if this has improved by checking https://ag91.github.io/blog/2021/08/09/following-wise-suggestions-making-emacs-with-nyxt-more-consistent/

**Comment by ag91** [comment]
I will now look into the RSS
Edit: I have done some progress, but the first run failed. I will eventually make it work :P

**Comment by otech-nl** [comment]
Looks great now. Thanks!

**Comment by ag91** [comment]
I will close this, they told me I need to fix text size to be a bit bigger. I will do next post I publish. Please let me know if I can improve something.
