### ISSUE TITLE
no description in RSS

### ISSUE THREAD

**Issue by mbeppler** [ag91/ag91.github.io#2]
I read [Planet Emacslife](http://planet.emacslife.com) where your blog is a part of. Unfortunately your entries contain mostly no description and if, it is only a variation of the headline.

Your post always start with a very good TL;DR (Thanks for that). Why not include this as the description in your RSS feed?

This would help a lot by the decision to follow the link to your post or not.

**Comment by ag91** [comment]
ah, I didn't realize that. I can try to fix it though! I should also share the fork of org-page I use..

**Comment by ag91** [comment]
actually I have discovered that org-page inserts the blog contents by not setting a description in the org mode file for the post: so this is solved by changing my way of creating a blog (I always found boring to write a description at the last moment!).
Thanks for prompting me.
