### ISSUE TITLE
How to comment on this blog?

### ISSUE THREAD

**Issue by mbeppler** [ag91/ag91.github.io#3]
At the end of each article is *Comments* section. But how could I comment?

**Comment by ag91** [comment]
sorry, I should remove that as I don't wish to subscribe to Disquis. I usually link to Reddit the Emacs related blogs.
Sorry for the late reply, I missed this issue!

**Comment by ag91** [comment]
I removed the comments section to not confuse readers anymore, thanks for reporting this.
